language: php

php:
    - '5.6'
    - '7.0'


before_script:
  - pecl install -f mongodb-stable
  - composer install --dev --no-interaction --prefer-source

script: phpunit

notifications:
    on_success: never
    on_failure: always
